version: "3.8"
services:
  flask:
    build: .
    container_name: flask-app
    
    environment:
      FLASK_APP: app.py
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: my_db
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - 5000:5000

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

    networks:
      app-network:
        driver: bridge  
    volumes:
      - mysql-data:/var/lib/mysql